const express = require("express")
const app = express()
const dotenv = require("dotenv")
dotenv.config()
const mongoose = require("mongoose")
const cors = require("cors")
const router = require("./routes/routes.api")
app.listen(process.env.PORT, () => {
 console.log(`Server is running on port ${process.env.PORT}`)   
})
mongoose.connect(process.env.DATABASE).then(() => {console.log("Database connected")}).catch(() => {
 console.log("Failed to connect")
})
app.use(express.json())
app.use(cors())
app.use("/api", router)